import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexProviderWithClerk";
import ThemeProvider from "../providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import "@uploadthing/react/styles.css";

const inter = Roboto_Slab({ 
  subsets: ["latin"], 
  weight : ['400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Tasks Drive",
  description: "Generated by Mehdi Znayzen",
  icons : '/logo.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <body className={cn(inter.className, 'overflow-x-hidden')}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster />
              {children}
            </ThemeProvider>
        </body>
      </ConvexClientProvider>
    </html>
  );
}
